apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecret.name }}
    creationPolicy: Owner
  data:
    - secretKey: API_KEY
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}